services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo

  reservations:
    image: europe-central2-docker.pkg.dev/reservation-app-400319/reservation/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
    depends_on: 
      - mongo

  auth:
    image: europe-central2-docker.pkg.dev/reservation-app-400319/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: europe-central2-docker.pkg.dev/reservation-app-400319/payments/production
    ports:
      - '3003:3003'
    env_file:
    
      - ../apps/payments/.env
  notifications:
    image: europe-central2-docker.pkg.dev/reservation-app-400319/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo
